#!/usr/bin/python

import sys
sys.path.append("./include/midi/")
import midi

#histogram = [0] * 11
midifile = sys.argv[1]
stream = midi.read_midifile(midifile)
#for event in stream.iterevents():
#    if isinstance(event, midi.NoteEvent):
#        idx = event.pitch / 12
#        histogram[idx] += 1
#print histogram
stream.textdump()
